//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Development_Assignment
{
    public partial class CyberSecurityPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Label lblCourseTitle;
        protected global::System.Web.UI.WebControls.Button btnback;
    }
}
